# Generated by Django 2.0.2 on 2018-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
